# NumPy 2D array
Send Feedback
Problem Statement:
Given a 2D list, create a numpy 2D array using it.
Note: Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Print the Numpy array.
Output Format :
numpyArray

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np

# create a 2D list
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# create a NumPy 2D array using the 2D list
arr = np.array(lst)

# print the NumPy array
print(arr)


# NumPy 0s and 1s
Send Feedback
Problem Statement:
Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1.
Print the elements of array.
Output Format :
element1 element2 element3 ... 

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np

# create a NumPy array of size 10 with all values as 0
arr = np.zeros(10, dtype=int)

# set the fifth value to 1
arr[4] = 1

# print the elements of the array
for element in arr:
    print(element, end=' ')


# NumPy Inclusive
Send Feedback
Problem Statement:
Create an array with values ranging consecutively from 9 to 49 (both inclusive).
Print the Numpy array.
Output Format :
element1 element2 element3 ...

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np

# create a NumPy array with values ranging from 9 to 49 (both inclusive)
arr = np.arange(9, 50)

# print the elements of the array
for element in arr:
    print(element, end=' ')


# Identity Matrix
Send Feedback
Problem Statement:
Create a matrix having diagonal elements as 1 and all other elements as 0 of size (5, 6).
Print the Numpy array.
Output Format :
numpyArray

In [ ]:
import numpy as np

# create a 5x6 identity matrix using the np.identity() function
mat = np.identity(5, dtype=int)

# add a column of zeros to the matrix to make it 5x6
mat = np.concatenate((mat, np.zeros((5, 1), dtype=int)), axis=1)

# print the matrix
print(mat)


# Cut the Rope
Send Feedback
Problem Statement:
You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.
Note:Array elements are the points where cut is to be made and round upto 2 decimal place.
Print the array element.
Output Format :
element1 
element2 
element3

In [ ]:
# calculate the length of each part
length = 5 / 9

# initialize an empty list to store the cut positions
cuts = []

# loop through 8 times to make 8 cuts
for i in range(1, 9):
    # calculate the cut position and round to 2 decimal places
    cut = round(i * length, 2)
    # append the cut position to the cuts list
    cuts.append(cut)

# print the cut positions as separate lines
for cut in cuts:
    print(cut)


# Print Elements
Send Feedback
Problem Statement:
Given a 2D integer array size (4, 5) with name input_?
Print elements of highlighted matrix
Alt Text Alt Text Alt Text Alt Text

Output Format :
element1 element2 element3 . . .
element1 element2 element3 . . .
element1 element2 element3 . . .
element1 element2 element3 . . .

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
import numpy as np
input_ = np.arange(1,21,1)
input_ = input_.reshape(4,5)
print(*input_[2,:3])

print(*input_[1:4,3])

c = input_[2:4,:5]
print(*c[0],end=' ')
print(*c[1],end=' ')
print()

c = input_[1:3,1:3]
print(*c[0],end=' ')
print(*c[1],end=' ')

# Non-Zero elements
Send Feedback
Problem Statemnt:
Find indices of non-zero elements from the array [1,2,0,0,4,0] ?
Print the index of non-zero elements.
Output Format :
index1 index2 index3 ... 

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
arr = np.array([1,2,0,0,4,0])
ind = np.where(arr != 0)
print(*ind[0])

# Multiples of 3
Send Feedback
Problem Statement:
Given an integer array of size 10. Print the index of elements which are multiple of 3.
Note: Generate the following array
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
Print the index of elements.
Output Format :
index1 index2 index3 ... 

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
arr = np.array([1,2,0,0,4,0])
ind = np.where(arr != 0)

import numpy as np
arr = np.arange(1,20,2)
ind = np.where(arr%3 == 0)
print(*ind[0])

# Odd elements
Send Feedback
Problem Statemnt:
Given an integer array of size 10. Replace the odd number in numpy array with -1 ?
Note: Generate the following array
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Print the Numpy array.
Output Format :
firstElement secondElement  ... 

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
arr = np.arange(1,11)
arr[arr % 2 != 0] = -1
print(*arr)

# Replace Max
Send Feedback
Problem Statemnt:
Given an integer array of size 9 and replace the first occurrence of maximum value by 0?
Note: Generate the following array
array([11, 2, 13, 4, 15, 6, 27, 8, 19])
Print the Numpy array.
Output Format :
firstElement
secondElement 
... 

In [ ]:
import numpy as np
arr = np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
arr[arr.argmax()] = 0
for i in arr :
    print(i)

# Negate Elements
Send Feedback
Problem Statemnt:
Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?
Note: Generate the following array
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Print the Numpy array.
Output Format :
firstElement 
secondElement  
... 

In [ ]:
import numpy as np
arr = np.arange(1,11)
arr[2:8] = np.multiply(arr[2:8],-1)
for i in arr:
    print(i)

# Height
Send Feedback
Problem Statemnt:
Given age and height of 20 students in two different numpy arrays with name age and height (in cms). Print the age of those students whose height is above 155 cm.
Print the Numpy array.
Output Format :
age1 height1 
age2 height2 
... 

In [ ]:
import numpy as np
age = np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height = np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
index = np.where(height>155)
for i in range(len(index[0])) :
    print(age[index[0][i]],height[index[0][i]])

# Sort by column
Send Feedback
Problem Statemnt:
Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
That means, we should re-arrange complete row based on 2nd columns' values.
Given 2D array is:
 [[21 20 19 18 17]
  [16 15 14 13 12]
  [11 10  9  8  7]
  [ 6  5  4  3  2]]
Print the 2D array in sorted order.
Note you have to generate the 2D Array.Here 2nd column means column present at index 1.
Output Format :
[[ 6  5  4  3  2]
[11 10  9  8  7]
[16 15 14 13 12]
[21 20 19 18 17]]

In [ ]:
import numpy as np
arr = np.arange(21,1,-1)
arr = arr.reshape(4,5)
print(arr[::-1])

# Killed in USA
Send Feedback
Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
Find value of killed column only where country == ‘United States’?
Print 0 in place of missing values.
Print count of Killed as integer value.
Output Format :
Killed1
Killed2
Killed3
Killed4
. . .

In [ ]:
import numpy as np
import csv

with open('terrorismData.csv',encoding="utf8") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)

    killed = []
    country = []
    for row in data:
        killed.append(row['Killed'])
        country.append(row['Country'])

    np_killed = np.array(killed)
    np_country = np.array(country)
    
    np_killed[np_killed == ''] = '0.0'
    np_killed = np.array(np_killed,dtype=float)
    
    np_country = np.array(country)
    bool_arr = np_country=="United States"
    ans = np_killed[bool_arr]   
    for i in ans:
        print(int(i))
        import numpy as np

# Total Killed in USA
Send Feedback
Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
Find total number of people killed from USA?
Note: Some columns of killed are empty so replace them by 0.
Print count of Killed as integer value.
Output Format :
TotalKilled

In [ ]:
import numpy as np
import csv

with open('terrorismData.csv',encoding="utf8") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)

    killed = []
    country = []
    for row in data:
        killed.append(row['Killed'])
        country.append(row['Country'])

    np_killed = np.array(killed)
    np_country = np.array(country)
    
    np_killed[np_killed=='']= '0.0'
    np_killed = np.array(np_killed,dtype=float)
    
    np_country = np.array(country)
    bool_arr = np_country == "United States"
    ans = np_killed[bool_arr]
    
    print(int(np.sum(ans)))

# Terrorism Day
Send Feedback
Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
Find the number of attack held between day 10 and day 20?(ignoring the year and month)(including both day)
Print count of NumberOFAttack as integer value.
Output Format :
count

In [ ]:
import numpy as np
import csv

with open('terrorismData.csv',encoding="utf8") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)
    
    days = []
    for row in data:
        days.append(row['Day'])
        
    np_days = np.array(days, dtype=float)
    ans = np_days[(np_days>=10) & (np_days<=20)]
    print(len(ans))

# Terrorism Date
Send Feedback
Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
Find the number of attack held between 1 Jan 2010 and 31 Jan 2010?(including both date).
Note Ignore the case where day is 0
Print count of NumberOFAttack as integer value.
Output Format :

In [ ]:
import numpy as np
import csv

with open('terrorismData.csv',encoding="utf8") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)
    
    days = []
    months = []
    year = []
    for row in data:
        days.append(row['Day'])
        months.append(row['Month'])
        year.append(row['Year'])
        
    np_day = np.array(days, dtype=float)
    np_month = np.array(months, dtype=float)
    np_year = np.array(year, dtype=float)
    
    np_day = np_day[np_month==1]
    np_year = np_year[np_month==1]
    np_day = np_day[np_year==2010]
    
    print(len(np_day[np_day!=0]))

# Terror Casualty Attack
Send Feedback
Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
As we knew the Kargil ( in Jammu and Kashmir) War that took place between May 1999 and July 1999 (3 Months) ,so there was a huge conflict in Kashmir Valley during this period.
In this dataset, there is no information regarding the war between the two countries to find out the casualty during the war.
So find out the attack in this period in which maximum casualties happened.
Print the count of casualties (as integer), city in which that attack happened and name of attack group.
Note : Casualty = Killed + Wounded.Fill the empty value in killed or wounded feature to 0.
Output Format :
Casualty City TerroristGroup

In [ ]:
import numpy as np
import csv

with open('terrorismData.csv',encoding="utf8") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)
    
    city = []
    casualty = []
    for row in data:
        if row["State"] == "Jammu and Kashmir" and row["Year"] == "1999" :
            if row["Month"] =="5" or row["Month"] == "6" or row["Month"] == "7" :
                casualty.append([row["Killed"],row["Wounded"]])
                city.append([row["City"],row['Group']])
                
    np_city = np.array(city)
    np_casualty = np.array(casualty)
    
    np_casualty[np_casualty==''] = "0.0"
    np_casualty = np.array(np_casualty, dtype = float)
    
    np_casualty = np.sum(np_casualty, axis=1)
    index = np.argmax(np_casualty)
    print(int(np_casualty[index]),np_city[index][0],np_city[index][1])

# Terror Casualty Red
Send Feedback
Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
Find the casualty in the Red Corridor States ? Mainly Red corridor states include Jharkhand, Odisha, Andhra Pradesh, and Chhattisgarh.
Note: Casualty=Killed +Wounded
Print count of Casualty as integer value.

In [ ]:
import numpy as np
import csv

with open('terrorismData.csv',encoding="utf8") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)
    
    casualty = []
    for row in data:
        if row['State']=='Chhattisgarh' or row['State']=='Odisha' or row['State']=='Jharkhand' or row['State']=='Andhra Pradesh':
                casualty.append([row["Killed"],row["Wounded"]])

    np_casualty = np.array(casualty)
    
    np_casualty[np_casualty==''] = "0.0"
    np_casualty = np.array(np_casualty, dtype = float)
    
    np_casualty = np.sum(np_casualty, axis=1)
    total_casualty = np.sum(np_casualty)
    print(int(total_casualty))

# Terror City Casualty
Send Feedback
Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
Find top 5 Indian Cities which has most number of casualties ?
Print top 5 cities along with total casualties in that city. Print count of Casualty as integer value.
Note: Ignoring the City which is Unknown.
Casualty = Killed + Wounded.
Output Format :
city_1 casualty_1
city_2 casualty_2
city_3 casualty_3
city_4 casualty_4

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given formatimport numpy as np
import csv
from collections import Counter

with open('terrorismData.csv',encoding="utf8") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)
    
    city = []
    casualty = []
    for row in data:
         if row["Country"] == 'India' and row['City'] != 'Unknown':
                casualty.append([row["Killed"],row["Wounded"]])
                city.append(row["City"])
                
    np_city = np.array(city)
    np_casualty = np.array(casualty)
    
    np_casualty[np_casualty==''] = "0.0"
    np_casualty = np.array(np_casualty, dtype = float)
    np_casualty = np.sum(np_casualty, axis=1)
    
    dic = {}
    for i in range(len(np_city)):
        if np_city[i] in dic:
            dic[np_city[i]] += np_casualty[i]
        else:
            dic[np_city[i]] = np_casualty[i]

    k = Counter(dic) 
    high = k.most_common(5) 
    for i in high: 
        print(i[0],int(i[1]))

# Terrorism FrequentDay
Send Feedback
Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
Find the most frequent day of attack in a terrorismDataset ?
Note: Here np.unique can be used.
Print count of frequent day and number of attack as Integer value.

In [ ]:
import numpy as np
import csv

with open('terrorismData.csv',encoding="utf8") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)
    
    day = []
    for row in data:
        day.append(row['Day'])
        
    np_day = np.array(day, dtype='int')
    day, count = np.unique(np_day, return_counts=True)
    index = np.argmax(count)
    print(day[index], count[index])